import { motion } from 'framer-motion';
import { Link } from 'react-router-dom';
import { createPageUrl } from '@/utils';
import {
  Globe, TrendingUp, Zap, Search, ShieldCheck, BarChart2,
  MonitorSmartphone, ArrowRight, Lightbulb, AlertTriangle, CheckCircle2
} from 'lucide-react';
import Navbar from '@/components/home/Navbar';
import FooterSection from '@/components/home/FooterSection';
import GlassCard from '@/components/ui/GlassCard';

const stats = [
  { value: '75%', label: 'of users judge a business\'s credibility by its website design' },
  { value: '53%', label: 'of mobile users abandon sites that take over 3 seconds to load' },
  { value: '70%', label: 'of small businesses without a website miss out on online customers' },
  { value: '14×', label: 'more leads generated by businesses with active SEO strategies' },
];

const articles = [
  {
    icon: Globe,
    tag: 'Foundation',
    title: 'Why Your Website Is Your Most Powerful Business Asset',
    summary: 'In today\'s digital economy, your website is often the first — and sometimes only — impression a potential customer has of your business. A poorly designed or slow website costs you sales every single day without you even knowing it.',
    points: [
      'Your website works 24/7 as your best salesperson',
      'First impressions happen in under 0.05 seconds',
      'A professional site builds instant trust and authority',
      'It\'s the hub of all your digital marketing efforts',
    ],
    color: 'from-emerald-500/10 to-emerald-900/5',
    accent: 'text-emerald-600',
  },
  {
    icon: Zap,
    tag: 'Performance',
    title: 'Speed Is Revenue: The Hidden Cost of a Slow Website',
    summary: 'Website speed isn\'t just a technical metric — it\'s a business metric. Every second of delay in page load time can cost you a measurable percentage of conversions. Amazon famously calculated that 1 second of slowness cost them $1.6 billion per year.',
    points: [
      '1-second delay = up to 7% drop in conversions',
      'Google ranks faster sites higher in search results',
      'Mobile users are especially speed-sensitive',
      'Core Web Vitals now directly affect your SEO ranking',
    ],
    color: 'from-emerald-500/10 to-emerald-900/5',
    accent: 'text-emerald-700',
  },
  {
    icon: Search,
    tag: 'SEO',
    title: 'SEO: How Customers Find You Without You Paying for Ads',
    summary: 'Search Engine Optimisation (SEO) is the art and science of appearing at the top of Google when your ideal customer is searching for what you offer. Unlike paid ads, organic traffic compounds over time — meaning the investment keeps paying back.',
    points: [
      '68% of online experiences begin with a search engine',
      'The #1 Google result gets ~31% of all clicks',
      'SEO leads have a 14.6% close rate vs 1.7% for outbound',
      'Technical SEO fixes can double your visibility overnight',
    ],
    color: 'from-emerald-900/5 to-emerald-600/5',
    accent: 'text-[#0A3D2E]',
  },
  {
    icon: MonitorSmartphone,
    tag: 'Design',
    title: 'Mobile-First: Over 60% of Web Traffic Comes from Phones',
    summary: 'If your website doesn\'t look and work perfectly on a mobile phone, you\'re already losing more than half your potential customers. Mobile-first design isn\'t an upgrade — it\'s the baseline expectation in 2025.',
    points: [
      'Google uses mobile version of your site for indexing',
      'Poor mobile UX increases bounce rates dramatically',
      'Mobile shoppers are more likely to buy on a trusted site',
      'Responsive design directly impacts your conversion rate',
    ],
    color: 'from-emerald-400/10 to-emerald-800/5',
    accent: 'text-emerald-600',
  },
  {
    icon: ShieldCheck,
    tag: 'Audit',
    title: 'What a Website Audit Reveals (And Why You Need One)',
    summary: 'Most business owners assume their website is fine — until an audit reveals hidden issues costing them rankings, speed, and customers. A professional audit is like an X-ray for your digital presence: it shows exactly what\'s broken and what to fix.',
    points: [
      'Broken links and 404 errors that destroy user trust',
      'Duplicate content penalties from Google',
      'Missing meta tags and schema markup',
      'Security vulnerabilities that put your visitors at risk',
    ],
    color: 'from-emerald-900/8 to-emerald-500/5',
    accent: 'text-[#0A3D2E]',
  },
  {
    icon: TrendingUp,
    tag: 'Growth',
    title: 'Conversion Rate Optimisation: Turn Visitors into Customers',
    summary: 'Getting traffic to your website is only half the battle. CRO (Conversion Rate Optimisation) focuses on turning the visitors you already have into paying customers — without spending more on ads.',
    points: [
      'A clear CTA can increase conversions by 371%',
      'Trust signals (reviews, logos) dramatically boost sales',
      'Simplified forms reduce drop-off rates significantly',
      'Strategic page structure guides users to take action',
    ],
    color: 'from-emerald-600/10 to-emerald-300/5',
    accent: 'text-emerald-600',
  },
];

const warnings = [
  { icon: AlertTriangle, text: 'Using a free website builder with no custom domain damages credibility' },
  { icon: AlertTriangle, text: 'No SSL certificate (HTTPS) causes browsers to warn users away' },
  { icon: AlertTriangle, text: 'Not appearing on Google Maps / local search costs foot traffic' },
  { icon: AlertTriangle, text: 'Outdated design signals an outdated business to new visitors' },
];

export default function Insights() {
  return (
    <div className="min-h-screen bg-[#F5F5F3] overflow-x-hidden">
      <style>{`* { font-family: 'Inter', sans-serif; } ::selection { background: rgba(52,211,153,0.2); }`}</style>
      <Navbar />

      {/* Hero */}
      <section className="pt-36 pb-20 px-6 relative overflow-hidden">
        <div className="absolute top-20 right-0 w-[500px] h-[500px] bg-emerald-400/5 rounded-full blur-3xl pointer-events-none" />
        <div className="absolute bottom-0 left-0 w-80 h-80 bg-emerald-600/5 rounded-full blur-2xl pointer-events-none" />
        <div className="max-w-5xl mx-auto text-center">
          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.7 }}>
            <div className="inline-flex items-center gap-2 bg-emerald-50 border border-emerald-200 rounded-full px-4 py-2 text-emerald-700 text-xs font-medium tracking-widest uppercase mb-6">
              <Lightbulb className="w-3.5 h-3.5" /> Web Insights for Business Owners
            </div>
            <h1 className="text-5xl md:text-6xl font-bold text-[#0A3D2E] tracking-tight leading-tight mb-6">
              What every business owner<br />
              <span className="italic font-light">should know about the web</span>
            </h1>
            <p className="text-gray-500 text-lg max-w-2xl mx-auto leading-relaxed">
              Your website is more than a digital brochure. It's your hardest-working employee, your brand's first handshake, and your biggest growth lever — if it's built right.
            </p>
          </motion.div>
        </div>
      </section>

      {/* Stats Banner */}
      <section className="py-12 px-6">
        <div className="max-w-6xl mx-auto">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            {stats.map((s, i) => (
              <motion.div
                key={i}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.1 }}
                className="bg-white rounded-2xl p-6 border border-gray-100 shadow-sm text-center"
              >
                <div className="text-3xl font-black text-[#0A3D2E] mb-2">{s.value}</div>
                <div className="text-xs text-gray-400 leading-relaxed">{s.label}</div>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* Warning Signs */}
      <section className="py-10 px-6">
        <div className="max-w-6xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="bg-emerald-50 border border-emerald-200 rounded-3xl p-8"
          >
            <h3 className="text-lg font-bold text-[#0A3D2E] mb-5 flex items-center gap-2">
              <AlertTriangle className="w-5 h-5 text-emerald-600" /> Is Your Website Hurting Your Business?
            </h3>
            <div className="grid sm:grid-cols-2 gap-3">
              {warnings.map((w, i) => (
                <div key={i} className="flex items-start gap-3 text-sm text-[#0A3D2E]/80">
                  <w.icon className="w-4 h-4 shrink-0 mt-0.5 text-emerald-500" />
                  {w.text}
                </div>
              ))}
            </div>
            <Link to={createPageUrl('Contact')}>
              <motion.button
                whileHover={{ scale: 1.03 }}
                whileTap={{ scale: 0.97 }}
                className="mt-6 px-6 py-3 bg-gradient-to-r from-[#0A3D2E] to-emerald-700 text-white text-sm font-medium rounded-full flex items-center gap-2 shadow-lg shadow-emerald-900/15"
              >
                Get a Free Website Review <ArrowRight className="w-4 h-4" />
              </motion.button>
            </Link>
          </motion.div>
        </div>
      </section>

      {/* Articles */}
      <section className="py-16 px-6">
        <div className="max-w-6xl mx-auto">
          <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="mb-12">
            <span className="text-emerald-600 text-sm font-medium tracking-[0.2em] uppercase">Deep Dives</span>
            <h2 className="text-4xl font-bold text-[#0A3D2E] mt-3 tracking-tight">
              The knowledge that <span className="italic font-light">changes the game</span>
            </h2>
          </motion.div>

          <div className="space-y-8">
            {articles.map((article, i) => (
              <motion.div
                key={i}
                initial={{ opacity: 0, y: 30 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.6, delay: i * 0.08 }}
              >
                <GlassCard className={`p-8 bg-gradient-to-br ${article.color}`} delay={0}>
                  <div className="grid md:grid-cols-2 gap-8 items-start">
                    <div>
                      <div className="flex items-center gap-3 mb-4">
                        <div className="w-10 h-10 rounded-xl bg-white/70 flex items-center justify-center shadow-sm">
                          <article.icon className={`w-5 h-5 ${article.accent}`} strokeWidth={1.5} />
                        </div>
                        <span className={`text-xs font-semibold tracking-widest uppercase ${article.accent}`}>{article.tag}</span>
                      </div>
                      <h3 className="text-xl font-bold text-[#0A3D2E] mb-3 leading-snug">{article.title}</h3>
                      <p className="text-sm text-gray-500 leading-relaxed">{article.summary}</p>
                    </div>
                    <div>
                      <p className="text-xs font-semibold text-gray-400 uppercase tracking-widest mb-4">Key Takeaways</p>
                      <div className="space-y-3">
                        {article.points.map((point, j) => (
                          <div key={j} className="flex items-start gap-3 text-sm text-gray-600">
                            <CheckCircle2 className="w-4 h-4 text-emerald-500 shrink-0 mt-0.5" />
                            {point}
                          </div>
                        ))}
                      </div>
                    </div>
                  </div>
                </GlassCard>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="py-20 px-6">
        <div className="max-w-4xl mx-auto">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="bg-gradient-to-br from-[#0A3D2E] to-emerald-700 rounded-3xl p-12 text-center relative overflow-hidden"
          >
            <div className="absolute inset-0 opacity-10" style={{ backgroundImage: 'radial-gradient(circle at 70% 30%, #fff 1px, transparent 1px)', backgroundSize: '30px 30px' }} />
            <div className="relative z-10">
              <h2 className="text-3xl md:text-4xl font-bold text-white mb-4">
                Ready to turn your website<br />into a growth machine?
              </h2>
              <p className="text-emerald-200 text-sm mb-8 max-w-xl mx-auto leading-relaxed">
                Let's audit what you have, identify what's holding you back, and build something that works for your business around the clock.
              </p>
              <div className="flex flex-col sm:flex-row gap-4 justify-center">
                <Link to={createPageUrl('Contact')}>
                  <motion.button
                    whileHover={{ scale: 1.04 }}
                    whileTap={{ scale: 0.97 }}
                    className="px-8 py-3.5 bg-white text-[#0A3D2E] font-semibold text-sm rounded-full flex items-center gap-2 shadow-xl"
                  >
                    Start a Conversation <ArrowRight className="w-4 h-4" />
                  </motion.button>
                </Link>
                <Link to={createPageUrl('Services')}>
                  <motion.button
                    whileHover={{ scale: 1.04 }}
                    whileTap={{ scale: 0.97 }}
                    className="px-8 py-3.5 bg-white/10 text-white border border-white/20 font-medium text-sm rounded-full hover:bg-white/20 transition-colors"
                  >
                    View Our Services
                  </motion.button>
                </Link>
              </div>
            </div>
          </motion.div>
        </div>
      </section>

      <FooterSection />
    </div>
  );
}